name: OSX
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.type }}-build
    runs-on: macos-latest
    strategy:
      matrix:
        type: [manager-osx]
      fail-fast: false
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.2'
      - uses: actions/checkout@v2

#      - name: Cache dependencies
#        uses: actions/cache@v2.1.3
#        with:
#          path: 3rdParty/buildCache
#          key: osx-${{ matrix.type }}-${{ hashFiles('3rdParty/*Mac*.sh', 'mac_build/dependencyNames.sh', 'mac_build/[bB]uild*.sh') }}

      - name: install dependencies
        run: ./3rdParty/buildMacDependencies.sh

      - name: make
        if: success()
        run: ./mac_build/buildMacBOINC-CI.sh --no_shared_headers

      - name: deploy
        if: ${{ success() }}
        run: echo "Would start deployment now"
        #run: ./deploy/prepare_deployment.sh ${BOINC_TYPE} deploy/${BOINC_TYPE}/ && ./deploy/deploy_to_bintray.sh deploy/${BOINC_TYPE}/
